### ISSUE TITLE
TODO: calculate how much you've paid for your education

### ISSUE THREAD

**Issue by particle** [taustation-fan/taustation-fan.github.io#8]
show the total credits spent on courses, if they've been pasted in the completed courses section

**Comment by duelafn** [comment]
Similarly, I was thinking it would be nice to see segments (days?) completed and remaining. Perhaps as "Segments completed: XXX of YYY (ZZZ remaining)"

**Comment by Perleone** [comment]
Segments completed/remaining pertaining to what exactly? The currently enrolled course or the total of done vs available courses?

**Comment by duelafn** [comment]
Sorry, total courses (e.g., it will take you 273 days to complete the rest of the courses) since it can't really know how long until the current is over (the past info only reports day of completion not time).

Hmm... Though thinking more about it, I guess to be remotely useful dealing with that it would need some options (your intelligence stat and whether you plan to spend bonds), so perhaps the scope of reporting time remaining is too much.

**Comment by particle** [comment]
implemented at taustation-fan/university, and live at education.tauguide.de
